extends Node

var ingredients_roster: Dictionary = {
	"amber" = {
		"name" = "Amber",
		"rarity" = "common",
		"icon" = preload("res://assets/ingredients/amber.png"),
		"combat" = 9,
		"utility" = 5,
		"whimsy" = 4,
		"description" = "This chunk of petrified tree sap is prized for its color and gem-like luster and is often used in jewelry. Somearcane jewelers claim that it has special properties, especially if an ancient insect is trapped within it. Amber can be found in rocky areas where petrifi ed wood is found, and it has been known to wash up on certain beaches.",
		"discovered" = false,
		"stats_discovered" = false,
	},
	"apper_carrot" = {
		"name" = "Apper Carrot",
		"rarity" = "common",
		"icon" = preload("res://assets/ingredients/apper_carrot.png"),
		"combat" = 0,
		"utility" = 3,
		"whimsy" = 1,
		"description" = "The Apper Carrot is well known throughout Obojima as a superior strain of carrot that has a delicious flavor and a hearty crunch. Its bulbous top peeks out from the soil when it’s ready for harvesting, making it easy for foragers to spot Apper Carrots in the wild. They can be found in most grassy lowland areas.",
		"discovered" = false,
		"stats_discovered" = false,
	},
	"bamboo" = {
		"name" = "Bamboo",
		"rarity" = "common",
		"icon" = preload("res://assets/ingredients/bamboo.png"),
		"combat" = 3,
		"utility" = 3,
		"whimsy" = 3,
		"description" = "Used in everything from building material to drinking vessels and musical instruments, bamboo is perhaps the most versatile material on the island. Patches of bamboo can be found in most places on Obojima, however there are a few bamboo forests in the foothills and mountainous regions where it can grow as thick as a tree.",
		"discovered" = false,
		"stats_discovered" = false,
	},
	"bashu_powder" = {
		"name" = "Bashu Powder",
		"rarity" = "common",
		"icon" = preload("res://assets/ingredients/bashu_powder.png"),
		"combat" = 2,
		"utility" = 0,
		"whimsy" = 0,
		"description" = "This russet powder is made from the ground seed pods of the bashu tree. Bashu powder is used commonly by chefs who want to add a spicy yet smoky flavor to their dishes. Most Obojimans believe that bashu powder also helps alleviate minor ailments like coughs and colds. Bashu trees are found inland in the warm and arid regions of Obojima.",
		"discovered" = false,
		"stats_discovered" = false,
	},
	"blue_back_salmon" = {
		"name" = "Blue Back Salmon",
		"rarity" = "common",
		"icon" = preload("res://assets/ingredients/blue_back_salmon.png"),
		"combat" = 3,
		"utility" = 4,
		"whimsy" = 7,
		"description" = "The fat-marbled, delicious fl esh of the blue back salmon are a staple in many villages across the island. A fully grown salmon can reach up to almost two meters in length and any fisherman will tell you that they are crafty, hard to catch, and can deliver a nasty bite. Blue back salmon are found in rivers all across Obojima and in the deepest parts of the surrounding reef.",
		"discovered" = false,
		"stats_discovered" = false,
	},
}
