extends Node

var potion_recipes = {
}

var potions_roster = {
	"combat" = {
		"1" = {
			"name" = "Rabbit's Speed",
			"rarity" = "uncommon",
			"icon" = preload("res://assets/potions/paranoia.png"),
			"discovered" = false,
			"description" = "test description",
		},
		"2" = {
			"name" = "Weapon Master's Elixir",
			"rarity" = "uncommon",
			"icon" = preload("res://assets/potions/paranoia.png"),
			"discovered" = false,
			"description" = "test description",
		},
		"3" = {
			"name" = "Spirit of Salyri",
			"rarity" = "uncommon",
			"icon" = preload("res://assets/potions/paranoia.png"),
			"discovered" = false,
			"description" = "test description",
		},
		"4" = {
			"name" = "Beast Hide",
			"rarity" = "uncommon",
			"icon" = preload("res://assets/potions/paranoia.png"),
			"discovered" = false,
			"description" = "test description",
		},
		"5" = {
			"name" = "Spirit Armor",
			"rarity" = "uncommon",
			"icon" = preload("res://assets/potions/paranoia.png"),
			"discovered" = false,
			"description" = "test description",
		},
		"6" = {
			"name" = "Displacement Field",
			"rarity" = "uncommon",
			"icon" = preload("res://assets/potions/paranoia.png"),
			"discovered" = false,
			"description" = "test description",
		},
		"7" = {
			"name" = "Shepherd's Bane",
			"rarity" = "uncommon",
			"icon" = preload("res://assets/potions/paranoia.png"),
			"discovered" = false,
			"description" = "test description",
		},
		"8" = {
			"name" = "Bottled Bomb",
			"rarity" = "uncommon",
			"icon" = preload("res://assets/potions/paranoia.png"),
			"discovered" = false,
			"description" = "test description",
		},
		"9" = {
			"name" = "Wonder Juice",
			"rarity" = "uncommon",
			"icon" = preload("res://assets/potions/paranoia.png"),
			"discovered" = false,
			"description" = "test description",
		},
		"10" = {
			"name" = "Candlecap",
			"rarity" = "uncommon",
			"icon" = preload("res://assets/potions/paranoia.png"),
			"discovered" = false,
			"description" = "test description",
		},
		"11" = {
			"name" = "Eagle's Vision",
			"rarity" = "uncommon",
			"icon" = preload("res://assets/potions/paranoia.png"),
			"discovered" = false,
			"description" = "test description",
		},
		"12" = {
			"name" = "Paranoia",
			"rarity" = "uncommon",
			"icon" = preload("res://assets/potions/paranoia.png"),
			"discovered" = false,
			"description" = "test description",
		},
		"13" = {
			"name" = "Bottled Torch",
			"rarity" = "uncommon",
			"icon" = preload("res://assets/potions/paranoia.png"),
			"discovered" = false,
			"description" = "test description",
		},
		"14" = {
			"name" = "Static Shock",
			"rarity" = "uncommon",
			"icon" = preload("res://assets/potions/paranoia.png"),
			"discovered" = false,
			"description" = "test description",
		},
		"15" = {
			"name" = "Incoming!",
			"rarity" = "uncommon",
			"icon" = preload("res://assets/potions/paranoia.png"),
			"discovered" = false,
			"description" = "test description",
		},
		"16" = {
			"name" = "Lightning Breath",
			"rarity" = "uncommon",
			"icon" = preload("res://assets/potions/paranoia.png"),
			"discovered" = false,
			"description" = "test description",
		},
		"17" = {
			"name" = "Heroism",
			"rarity" = "uncommon",
			"icon" = preload("res://assets/potions/paranoia.png"),
			"discovered" = false,
			"description" = "test description",
		},
		"18" = {
			"name" = "Slugskin",
			"rarity" = "uncommon",
			"icon" = preload("res://assets/potions/paranoia.png"),
			"discovered" = false,
			"description" = "test description",
		},
		"19" = {
			"name" = "Thunderbelch",
			"rarity" = "uncommon",
			"icon" = preload("res://assets/potions/paranoia.png"),
			"discovered" = false,
			"description" = "test description",
		},
		"20" = {
			"name" = "Seeking Smoke",
			"rarity" = "uncommon",
			"icon" = preload("res://assets/potions/paranoia.png"),
			"discovered" = false,
			"description" = "test description",
		},
		"21" = {
			"name" = "Dancing Juice",
			"rarity" = "uncommon",
			"icon" = preload("res://assets/potions/paranoia.png"),
			"discovered" = false,
			"description" = "test description",
		},
		"22" = {
			"name" = "Prickleskin",
			"rarity" = "uncommon",
			"icon" = preload("res://assets/potions/paranoia.png"),
			"discovered" = false,
			"description" = "test description",
		},
		"23" = {
			"name" = "Tiny Bubbles",
			"rarity" = "uncommon",
			"icon" = preload("res://assets/potions/paranoia.png"),
			"discovered" = false,
			"description" = "test description",
		},
		"24" = {
			"name" = "Claws of the Crab King",
			"rarity" = "uncommon",
			"icon" = preload("res://assets/potions/paranoia.png"),
			"discovered" = false,
			"description" = "test description",
		},
		"25" = {
			"name" = "Rubberskin",
			"rarity" = "uncommon",
			"icon" = preload("res://assets/potions/paranoia.png"),
			"discovered" = false,
			"description" = "test description",
		},
		"26" = {
			"name" = "Keening Voice",
			"rarity" = "uncommon",
			"icon" = preload("res://assets/potions/paranoia.png"),
			"discovered" = false,
			"description" = "test description",
		},
		"27" = {
			"name" = "Kinetic Pop",
			"rarity" = "uncommon",
			"icon" = preload("res://assets/potions/paranoia.png"),
			"discovered" = false,
			"description" = "test description",
		},
		"28" = {
			"name" = "Healing Gas",
			"rarity" = "uncommon",
			"icon" = preload("res://assets/potions/paranoia.png"),
			"discovered" = false,
			"description" = "test description",
		},
		"29" = {
			"name" = "Cinderskin",
			"rarity" = "uncommon",
			"icon" = preload("res://assets/potions/paranoia.png"),
			"discovered" = false,
			"description" = "test description",
		},
		"30" = {
			"name" = "Iron Mind",
			"rarity" = "uncommon",
			"icon" = preload("res://assets/potions/paranoia.png"),
			"discovered" = false,
			"description" = "test description",
		},
	},
	"utility" = {
		"1" = {
			"name" = "Sensorius Maximus",
			"rarity" = "uncommon",
			"icon" = preload("res://assets/potions/paranoia.png"),
			"discovered" = false,
			"description" = "test description",
		},
		"2" = {
			"name" = "Flip and Skip",
			"rarity" = "uncommon",
			"icon" = preload("res://assets/potions/paranoia.png"),
			"discovered" = false,
			"description" = "test description",
		},
		"3" = {
			"name" = "Brute Brew",
			"rarity" = "uncommon",
			"icon" = preload("res://assets/potions/paranoia.png"),
			"discovered" = false,
			"description" = "test description",
		},
		"4" = {
			"name" = "Animal Affinity",
			"rarity" = "uncommon",
			"icon" = preload("res://assets/potions/paranoia.png"),
			"discovered" = false,
			"description" = "test description",
		},
		"5" = {
			"name" = "Detective's Tonic",
			"rarity" = "uncommon",
			"icon" = preload("res://assets/potions/paranoia.png"),
			"discovered" = false,
			"description" = "test description",
		},
		"6" = {
			"name" = "Cave Diver",
			"rarity" = "uncommon",
			"icon" = preload("res://assets/potions/paranoia.png"),
			"discovered" = false,
			"description" = "test description",
		},
		"7" = {
			"name" = "Perfect Memory",
			"rarity" = "uncommon",
			"icon" = preload("res://assets/potions/paranoia.png"),
			"discovered" = false,
			"description" = "test description",
		},
		"8" = {
			"name" = "Eyes of Akibu",
			"rarity" = "uncommon",
			"icon" = preload("res://assets/potions/paranoia.png"),
			"discovered" = false,
			"description" = "test description",
		},
		"9" = {
			"name" = "Glowskin",
			"rarity" = "uncommon",
			"icon" = preload("res://assets/potions/paranoia.png"),
			"discovered" = false,
			"description" = "test description",
		},
		"10" = {
			"name" = "Tiny Telekinesis",
			"rarity" = "uncommon",
			"icon" = preload("res://assets/potions/paranoia.png"),
			"discovered" = false,
			"description" = "test description",
		},
		"11" = {
			"name" = "Irresistible Charm",
			"rarity" = "uncommon",
			"icon" = preload("res://assets/potions/paranoia.png"),
			"discovered" = false,
			"description" = "test description",
		},
		"12" = {
			"name" = "Pathseeking",
			"rarity" = "uncommon",
			"icon" = preload("res://assets/potions/paranoia.png"),
			"discovered" = false,
			"description" = "test description",
		},
		"13" = {
			"name" = "Iron Belly",
			"rarity" = "uncommon",
			"icon" = preload("res://assets/potions/paranoia.png"),
			"discovered" = false,
			"description" = "test description",
		},
		"14" = {
			"name" = "Face of Fugari",
			"rarity" = "uncommon",
			"icon" = preload("res://assets/potions/paranoia.png"),
			"discovered" = false,
			"description" = "test description",
		},
		"15" = {
			"name" = "Duck Foot",
			"rarity" = "uncommon",
			"icon" = preload("res://assets/potions/paranoia.png"),
			"discovered" = false,
			"description" = "test description",
		},
		"16" = {
			"name" = "Potion of Fog",
			"rarity" = "uncommon",
			"icon" = preload("res://assets/potions/paranoia.png"),
			"discovered" = false,
			"description" = "test description",
		},
		"17" = {
			"name" = "Secret Path",
			"rarity" = "uncommon",
			"icon" = preload("res://assets/potions/paranoia.png"),
			"discovered" = false,
			"description" = "test description",
		},
		"18" = {
			"name" = "Grandma's Turnip Soup",
			"rarity" = "uncommon",
			"icon" = preload("res://assets/potions/paranoia.png"),
			"discovered" = false,
			"description" = "test description",
		},
		"19" = {
			"name" = "Herbalist's Aid",
			"rarity" = "uncommon",
			"icon" = preload("res://assets/potions/paranoia.png"),
			"discovered" = false,
			"description" = "test description",
		},
		"20" = {
			"name" = "Homeward Tonic",
			"rarity" = "uncommon",
			"icon" = preload("res://assets/potions/paranoia.png"),
			"discovered" = false,
			"description" = "test description",
		},
		"21" = {
			"name" = "Soft Paw",
			"rarity" = "uncommon",
			"icon" = preload("res://assets/potions/paranoia.png"),
			"discovered" = false,
			"description" = "test description",
		},
		"22" = {
			"name" = "Potion of Healing Touch",
			"rarity" = "uncommon",
			"icon" = preload("res://assets/potions/paranoia.png"),
			"discovered" = false,
			"description" = "test description",
		},
		"23" = {
			"name" = "Cat's Eye",
			"rarity" = "uncommon",
			"icon" = preload("res://assets/potions/paranoia.png"),
			"discovered" = false,
			"description" = "test description",
		},
		"24" = {
			"name" = "Liquid Mending",
			"rarity" = "uncommon",
			"icon" = preload("res://assets/potions/paranoia.png"),
			"discovered" = false,
			"description" = "test description",
		},
		"25" = {
			"name" = "Liquid Lockpick",
			"rarity" = "uncommon",
			"icon" = preload("res://assets/potions/paranoia.png"),
			"discovered" = false,
			"description" = "test description",
		},
		"26" = {
			"name" = "Language Lore",
			"rarity" = "uncommon",
			"icon" = preload("res://assets/potions/paranoia.png"),
			"discovered" = false,
			"description" = "test description",
		},
		"27" = {
			"name" = "Pig Snout",
			"rarity" = "uncommon",
			"icon" = preload("res://assets/potions/paranoia.png"),
			"discovered" = false,
			"description" = "test description",
		},
		"28" = {
			"name" = "Machine Oil",
			"rarity" = "uncommon",
			"icon" = preload("res://assets/potions/paranoia.png"),
			"discovered" = false,
			"description" = "test description",
		},
		"29" = {
			"name" = "Potion of Soft Steps",
			"rarity" = "uncommon",
			"icon" = preload("res://assets/potions/paranoia.png"),
			"discovered" = false,
			"description" = "test description",
		},
		"30" = {
			"name" = "Liquid Cat",
			"rarity" = "uncommon",
			"icon" = preload("res://assets/potions/paranoia.png"),
			"discovered" = false,
			"description" = "test description",
		},
	},
	"whimsy" = {
		"1" = {
			"name" = "Melodious Bird Calls",
			"rarity" = "uncommon",
			"icon" = preload("res://assets/potions/paranoia.png"),
			"discovered" = false,
			"description" = "test description",
		},
		"2" = {
			"name" = "Projected Thoughts",
			"rarity" = "uncommon",
			"icon" = preload("res://assets/potions/paranoia.png"),
			"discovered" = false,
			"description" = "test description",
		},
		"3" = {
			"name" = "Intoxicating Aroma",
			"rarity" = "uncommon",
			"icon" = preload("res://assets/potions/paranoia.png"),
			"discovered" = false,
			"description" = "test description",
		},
		"4" = {
			"name" = "Ladybug Kinship",
			"rarity" = "uncommon",
			"icon" = preload("res://assets/potions/paranoia.png"),
			"discovered" = false,
			"description" = "test description",
		},
		"5" = {
			"name" = "Essence of Umami",
			"rarity" = "uncommon",
			"icon" = preload("res://assets/potions/paranoia.png"),
			"discovered" = false,
			"description" = "test description",
		},
		"6" = {
			"name" = "Vocal Stranger",
			"rarity" = "uncommon",
			"icon" = preload("res://assets/potions/paranoia.png"),
			"discovered" = false,
			"description" = "test description",
		},
		"7" = {
			"name" = "Beard Brew",
			"rarity" = "uncommon",
			"icon" = preload("res://assets/potions/paranoia.png"),
			"discovered" = false,
			"description" = "test description",
		},
		"8" = {
			"name" = "Photosynthetic Skin",
			"rarity" = "uncommon",
			"icon" = preload("res://assets/potions/paranoia.png"),
			"discovered" = false,
			"description" = "test description",
		},
		"9" = {
			"name" = "Paradise Plumage",
			"rarity" = "uncommon",
			"icon" = preload("res://assets/potions/paranoia.png"),
			"discovered" = false,
			"description" = "test description",
		},
		"10" = {
			"name" = "Musical Mixer",
			"rarity" = "uncommon",
			"icon" = preload("res://assets/potions/paranoia.png"),
			"discovered" = false,
			"description" = "test description",
		},
		"11" = {
			"name" = "Stink Brew",
			"rarity" = "uncommon",
			"icon" = preload("res://assets/potions/paranoia.png"),
			"discovered" = false,
			"description" = "test description",
		},
		"12" = {
			"name" = "Duko the Trickster's Elixir",
			"rarity" = "uncommon",
			"icon" = preload("res://assets/potions/paranoia.png"),
			"discovered" = false,
			"description" = "test description",
		},
		"13" = {
			"name" = "Manifested Nostalgia",
			"rarity" = "uncommon",
			"icon" = preload("res://assets/potions/paranoia.png"),
			"discovered" = false,
			"description" = "test description",
		},
		"14" = {
			"name" = "Pigment",
			"rarity" = "uncommon",
			"icon" = preload("res://assets/potions/paranoia.png"),
			"discovered" = false,
			"description" = "test description",
		},
		"15" = {
			"name" = "Audio Oddity",
			"rarity" = "uncommon",
			"icon" = preload("res://assets/potions/paranoia.png"),
			"discovered" = false,
			"description" = "test description",
		},
		"16" = {
			"name" = "Hindsight",
			"rarity" = "uncommon",
			"icon" = preload("res://assets/potions/paranoia.png"),
			"discovered" = false,
			"description" = "test description",
		},
		"17" = {
			"name" = "Super Singing",
			"rarity" = "uncommon",
			"icon" = preload("res://assets/potions/paranoia.png"),
			"discovered" = false,
			"description" = "test description",
		},
		"18" = {
			"name" = "Fluffplum Tonic",
			"rarity" = "uncommon",
			"icon" = preload("res://assets/potions/paranoia.png"),
			"discovered" = false,
			"description" = "test description",
		},
		"19" = {
			"name" = "Merriment",
			"rarity" = "uncommon",
			"icon" = preload("res://assets/potions/paranoia.png"),
			"discovered" = false,
			"description" = "test description",
		},
		"20" = {
			"name" = "Bubble Message",
			"rarity" = "uncommon",
			"icon" = preload("res://assets/potions/paranoia.png"),
			"discovered" = false,
			"description" = "test description",
		},
		"21" = {
			"name" = "Crystal Clear",
			"rarity" = "uncommon",
			"icon" = preload("res://assets/potions/paranoia.png"),
			"discovered" = false,
			"description" = "test description",
		},
		"22" = {
			"name" = "Elder Elixir",
			"rarity" = "uncommon",
			"icon" = preload("res://assets/potions/paranoia.png"),
			"discovered" = false,
			"description" = "test description",
		},
		"23" = {
			"name" = "Witch's Hidden Gem",
			"rarity" = "uncommon",
			"icon" = preload("res://assets/potions/paranoia.png"),
			"discovered" = false,
			"description" = "test description",
		},
		"24" = {
			"name" = "Carbonated Snake",
			"rarity" = "uncommon",
			"icon" = preload("res://assets/potions/paranoia.png"),
			"discovered" = false,
			"description" = "test description",
		},
		"25" = {
			"name" = "Shadow Child",
			"rarity" = "uncommon",
			"icon" = preload("res://assets/potions/paranoia.png"),
			"discovered" = false,
			"description" = "test description",
		},
		"26" = {
			"name" = "Hsirebbig",
			"rarity" = "uncommon",
			"icon" = preload("res://assets/potions/paranoia.png"),
			"discovered" = false,
			"description" = "test description",
		},
		"27" = {
			"name" = "Sky Swimming",
			"rarity" = "uncommon",
			"icon" = preload("res://assets/potions/paranoia.png"),
			"discovered" = false,
			"description" = "test description",
		},
		"28" = {
			"name" = "Passing Memory",
			"rarity" = "uncommon",
			"icon" = preload("res://assets/potions/paranoia.png"),
			"discovered" = false,
			"description" = "test description",
		},
		"29" = {
			"name" = "Bottled Slime",
			"rarity" = "uncommon",
			"icon" = preload("res://assets/potions/paranoia.png"),
			"discovered" = false,
			"description" = "test description",
		},
		"30" = {
			"name" = "Oil of the Trademark Flourish",
			"rarity" = "uncommon",
			"icon" = preload("res://assets/potions/paranoia.png"),
			"discovered" = false,
			"description" = "test description",
		},
	},
}
