extends Node

var potion_recipes = {
}

var potions_roster = {
	"combat" = {
		"1" = {
			"name" = "Rabbit's Speed",
			"rarity" = "uncommon",
			"icon" = preload("res://assets/potions/paranoia.png"),
			"discovered" = false,
			"description" = "test description",
		},
		"2" = {
			"name" = "Weapon Master's Elixir",
			"rarity" = "uncommon",
			"icon" = preload("res://assets/potions/paranoia.png"),
			"discovered" = false,
			"description" = "test description",
		},
		"3" = {
			"name" = "Spirit of Salyri",
			"rarity" = "uncommon",
			"icon" = preload("res://assets/potions/paranoia.png"),
			"discovered" = false,
			"description" = "test description",
		},
		"4" = {
			"name" = "Beast Hide",
			"rarity" = "uncommon",
			"icon" = preload("res://assets/potions/paranoia.png"),
			"discovered" = false,
			"description" = "test description",
		},
		"5" = {
			"name" = "Spirit Armor",
			"rarity" = "uncommon",
			"icon" = preload("res://assets/potions/paranoia.png"),
			"discovered" = false,
			"description" = "test description",
		},
		"6" = {
			"name" = "Displacement Field",
			"rarity" = "uncommon",
			"icon" = preload("res://assets/potions/paranoia.png"),
			"discovered" = false,
			"description" = "test description",
		},
		"7" = {
			"name" = "Shepherd's Bane",
			"rarity" = "uncommon",
			"icon" = preload("res://assets/potions/paranoia.png"),
			"discovered" = false,
			"description" = "test description",
		},
		"8" = {
			"name" = "Bottled Bomb",
			"rarity" = "uncommon",
			"icon" = preload("res://assets/potions/paranoia.png"),
			"discovered" = false,
			"description" = "test description",
		},
		"9" = {
			"name" = "Wonder Juice",
			"rarity" = "uncommon",
			"icon" = preload("res://assets/potions/paranoia.png"),
			"discovered" = false,
			"description" = "test description",
		},
		"10" = {
			"name" = "Candlecap",
			"rarity" = "uncommon",
			"icon" = preload("res://assets/potions/paranoia.png"),
			"discovered" = false,
			"description" = "test description",
		},
		"11" = {
			"name" = "Eagle's Vision",
			"rarity" = "uncommon",
			"icon" = preload("res://assets/potions/paranoia.png"),
			"discovered" = false,
			"description" = "test description",
		},
		"12" = {
			"name" = "Paranoia",
			"rarity" = "uncommon",
			"icon" = preload("res://assets/potions/paranoia.png"),
			"discovered" = false,
			"description" = "test description",
		},
		"13" = {
			"name" = "Bottled Torch",
			"rarity" = "uncommon",
			"icon" = preload("res://assets/potions/paranoia.png"),
			"discovered" = false,
			"description" = "test description",
		},
		"14" = {
			"name" = "Static Shock",
			"rarity" = "uncommon",
			"icon" = preload("res://assets/potions/paranoia.png"),
			"discovered" = false,
			"description" = "test description",
		},
		"15" = {
			"name" = "Incoming!",
			"rarity" = "uncommon",
			"icon" = preload("res://assets/potions/paranoia.png"),
			"discovered" = false,
			"description" = "test description",
		},
		"16" = {
			"name" = "Lightning Breath",
			"rarity" = "uncommon",
			"icon" = preload("res://assets/potions/paranoia.png"),
			"discovered" = false,
			"description" = "test description",
		},
		"17" = {
			"name" = "Heroism",
			"rarity" = "uncommon",
			"icon" = preload("res://assets/potions/paranoia.png"),
			"discovered" = false,
			"description" = "test description",
		},
		"18" = {
			"name" = "Slugskin",
			"rarity" = "uncommon",
			"icon" = preload("res://assets/potions/paranoia.png"),
			"discovered" = false,
			"description" = "test description",
		},
		"19" = {
			"name" = "Thunderbelch",
			"rarity" = "uncommon",
			"icon" = preload("res://assets/potions/paranoia.png"),
			"discovered" = false,
			"description" = "test description",
		},
		"20" = {
			"name" = "Seeking Smoke",
			"rarity" = "uncommon",
			"icon" = preload("res://assets/potions/paranoia.png"),
			"discovered" = false,
			"description" = "test description",
		},
		"21" = {
			"name" = "Dancing Juice",
			"rarity" = "uncommon",
			"icon" = preload("res://assets/potions/paranoia.png"),
			"discovered" = false,
			"description" = "test description",
		},
		"22" = {
			"name" = "Prickleskin",
			"rarity" = "uncommon",
			"icon" = preload("res://assets/potions/paranoia.png"),
			"discovered" = false,
			"description" = "test description",
		},
		"23" = {
			"name" = "Tiny Bubbles",
			"rarity" = "uncommon",
			"icon" = preload("res://assets/potions/paranoia.png"),
			"discovered" = false,
			"description" = "test description",
		},
		"24" = {
			"name" = "Claws of the Crab King",
			"rarity" = "uncommon",
			"icon" = preload("res://assets/potions/paranoia.png"),
			"discovered" = false,
			"description" = "test description",
		},
	},
}
